### ISSUE TITLE
logback-classic 1.5.5 breaks springProperty handle from included xml in a spring boot app, openjdk 17

### ISSUE THREAD

**Issue by binfeiruci** [qos-ch/logback#840] opened 2024-08-15 03:42 UTC
After updating to logback-classic 1.5.5, springProperty elements from included files break.

## error message
`ERROR in ch.qos.logback.core.joran.util.PropertySetter@551bc2c6 - Failed to invoke valueOf{} method in class [ch.qos.logback.core.util.FileSize] with value [maxFileSize_IS_UNDEFINED]`

## configs
included xml looks like:
`<springProperty scope="context" name="maxFileSize" source="logging.maxFileSize" defaultValue="100MB"/>`

## this reason
class `JoranConfigurator` method `buildModelInterpretationContext` making another instance of `JoranConfigurator`, not its subclass `SpringBootJoranConfigurator`.

## a fix
```
private JoranConfigurator makeAnotherInstance() {
        JoranConfigurator me = this;
        JoranConfigurator jc = new JoranConfigurator() {
            @Override
            protected void sanityCheck(Model topModel) {
                me.sanityCheck(topModel);
            }

            @Override
            protected void addModelHandlerAssociations(DefaultProcessor defaultProcessor) {
                me.addModelHandlerAssociations(defaultProcessor);
            }

            @Override
            public void addElementSelectorAndActionAssociations(RuleStore rs) {
                me.addElementSelectorAndActionAssociations(rs);
            }

            @Override
            public void processModel(Model model) {
                me.processModel(model);
            }
        };
        jc.setContext(context);
        return jc;
    }
```

**Comment by ceki** [comment] 2024-08-15 08:23
@binfeiruci  This issue seems like a duplicate of [issues/814](https://github.com/qos-ch/logback/issues/814). Closing as duplicate.

Please reopen if you do not agree.

**Closed by ceki** 2024-08-15 08:23 UTC
